name: 'ecma-402-biblio'

on:
  push:
    branches:
      - main

permissions:
  id-token: write # needed for trusted publishing
  contents: read

jobs:
  publish:
    name: 'publish ecma402-biblio'
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'tc39/ecma402' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish biblio
        run: scripts/publish-biblio.sh
