name: Require “Allow Edits”

on: [pull_request]

jobs:
  _:
    name: "Require “Allow Edits”"

    runs-on: ubuntu-latest

    steps:
    - uses: ljharb/require-allow-edits@b3932796b71a803b05968c8d7910e882baf4e6e6
